development:
  adapter: postgresql
  database: rcrd 
  host: localhost

test:
  adapter: postgresql
  database: rcrd_test 
  host: localhost

production:
  adapter: postgresql
  database: rcrd 
  host: localhost
  user: postgres 
  password: timanous
